---
title: "Group Projec 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#project will be done using SQL

#The project will consist of Justin and I coming together to use the SQL database to record the data obtained from the deer data collected from this years
 capstoe. The data consist of qualitative and quantitative data such as deer ID numbers, harvest date, 
 year, county, area name, age, sex among many other categories in which data was accounted for. Our goal as a whole is to be able to organize the obtained
 data in a way that is approchable and facilitates anaylsis of data once it comes to that. The data that has been generated thus far is currently recorded
 through an Excel sheet, and is in the process of being transfered to the SQL database as codes are generated and chosen fit for this project. 
 

 #This creates the Table and the add creates columns
 # The Varchar is the amount of character for the name of the column we did 50 so there is a confortarble amount of room incase the name is changed.
 # The decimal was added to Age and Weight as the data collected had decimals within.
 Create Table CapstoneCWD (
  ADD ODWC_ID int
  ADD Harvest_Date date
  ADD County Varchar (50)
  ADD Region Varchar (50)

  ADD Age decimal(5,1)
  ADD Sex VARCHAR(50)
  ADD Weight decimal(5,1)
  ADD Physical_Condition VARCHAR(50)
  ADD CWD VARCHAR(50);
  #This insetrts data into rows under the columns

  

ALTER TABLE CapstoneCWD;
 ADD Age decimal(5,1);
 ALTER TABLE CapstoneCWD;
 ADD Sex VARCHAR(50);
 ALTER TABLE CapstoneCWD;
 ADD Weight decimal(5,1);
 ALTER TABLE CapstoneCWD;
 ADD Physical_Condition VARCHAR(50);
 ALTER TABLE CapstoneCWD;
 ADD CWD VARCHAR(50);


       
       
       
        #This code inserts data into rows under the columns. The values imputed in the code must be in order with the 
        columns. You will notice that whole integers nor decimals require quotation marks as opposed to the other data types such as 
        data,and varchar(a series of characters). The data for each column is seperated by a coma, and each row is seperated by a set of
        parenthesis, in order to distinguish data sets from each other. Each set of parenthesis corresponds to a new row. We can execute
        this statement to insert multiple rows all at once. The semicolon seen at the end is the standard way to separate 
        each SQL statement in database systems that allow more than one SQL statement to be executed in the same call to the server.

  INSERT INTO CapstoneCWD
  VALUES (2318, "2023-02-13", "McIntosh", "NE", 6.5, "F", 110, "Good", "No),
         (2421, "2023-02-13", "McIntosh", "NE", 4.5, "F", 95.9, "Fair", "No"),
         (2346, "2023-02-06", "Stephens", "SW", 6.5, "F", 107, "Fair", "No"),
         (2356, "2023-02-06", "Stephens", "SW", 6.5, "F", 126, "Good", "No"),
         (2397, "2023-02-14", "Comanche", "SW", 1.5, "M", 101.7, "Good", "No"),
         (2486, "2023-02-20", "Beckham", "SW", 1.5, "F", 107, "Excellent", "No"),
         (2490, "2023-02-20", "Beckham", "SW", 3.5, "F", 120, "Excellent, "No"),
         (2347, "2023-02-21", "Jackson", "SW", 4.5, "F" 117, "Good", "No"),
         (2391, "2023-02-21", "Jackson", "SW" 1.5, "M", 71, "Good", "No"),
         (2437, "2023-02-15", "Adair", "NE", 0.5, "M", 68.5, "Fair", No"),
         (2432, "2023-02-15", "Adair", "NE", 1.5, "F", 88, "Excellent", "No"),
         (2342, "2023-02-06", "Muskogee", "NE", 6.5, "F", 104, "Good", "No");
         
         
         
  SELECT * FROM CapstoneCWD
       

  SELECT * FROM CapstoneCWD;
       
      #New rows were imputed in the same table CapstoneCWD at a different time, but the same procedure and code will apply 
      to the addtional statement made for the same reasons.      

INSERT INTO CapstoneCWD
VALUES (2372, "2023-02-06", "Muskogee", "NE", 3.5, "F", 99, "Good", "No"),
       (2425, "2023-02-28", "Ottawa", "NE", 4.5, "F", 113, "Excellent", "No"),
       (7518, "2023-02-28", "Ottawa", "NE", 3.5, "F", 132, "Excellent", "No"),
       (2398, "2023-01-31", "Roger Mills", "SW", 2.5, "F", 115.6, "Excellent", "No"),
       (2351, "2023-02-13", "Roger Mills", "SW", 3.5, "F", 123.0, "Excellent", "No"),
       (2399, "2023-02-13", "Custer", "SW", 3.5, "F", 104, "Excellent", "No"),
       (7519, "2023-02-27", "Osage", "NE", 5.5, "F", 93, "Fair", "No"),
       (144, "2023-02-27", "Osage", "NE", 5.5, "F", 94, "Fair", "No"),
       (2439, "2023-02-21", "Nowata", "NE", 3.5, "F", 96, "Good", "No"),
       (2304, "2023-02-21", "Nowata", "NE", 1.5, "F", 107.8, "Good", "No"),
       (2480, "2023-02-20", "Rogers", "NE", 1.5, "M", 100, "Good", "No"),
       (2468, "2023-02-20", "Rogers", "NE", 1.5, "F", 94, "Good", "No");

   SELECT * FROM CapstoneCWD
       

   SELECT * FROM CapstoneCWD;
       
       
       

